// Core MSA = 11-county official DFW-Plano-Arlington MSA
// (Dallas, Tarrant, Collin, Denton, Rockwall, Ellis, Johnson, Kaufman, Parker, Wise, Hunt)
// Extended = counties beyond the MSA boundary included for coverage completeness.

export const ZIP_GROUPS = [
  {
    label: 'East Corridor',
    region: 'core_msa' as const,
    zips: [
      { zip: '75087', label: 'Rockwall' },
      { zip: '75032', label: 'Rockwall Heath' },
      { zip: '75088', label: 'Rowlett' },
      { zip: '75089', label: 'Rowlett E' },
      { zip: '75098', label: 'Wylie' },
      { zip: '75132', label: 'Fate' },
      { zip: '75189', label: 'Royse City' },
      { zip: '75126', label: 'Forney' },
      { zip: '75160', label: 'Terrell' },
      { zip: '75161', label: 'Terrell E' },
      { zip: '75114', label: 'Crandall' },
      { zip: '75135', label: 'Caddo Mills' },
      { zip: '75150', label: 'Mesquite' },
      { zip: '75149', label: 'Mesquite S' },
      { zip: '75181', label: 'Mesquite E' },
      { zip: '75180', label: 'Mesquite SE' },
      { zip: '75182', label: 'Sunnyvale' },
      { zip: '75043', label: 'Garland E' },
      { zip: '75048', label: 'Sachse' },
      { zip: '75002', label: 'Allen' },
      { zip: '75013', label: 'Allen S' },
      { zip: '75070', label: 'McKinney W' },
      { zip: '75071', label: 'McKinney E' },
      { zip: '75072', label: 'McKinney S' },
      { zip: '75040', label: 'Garland W' },
      { zip: '75159', label: 'Seagoville' },
    ],
  },
  {
    label: 'North Dallas',
    region: 'core_msa' as const,
    zips: [
      { zip: '75034', label: 'Frisco W' },
      { zip: '75035', label: 'Frisco E' },
      { zip: '75033', label: 'Frisco N' },
      { zip: '75036', label: 'Frisco SW' },
      { zip: '75078', label: 'Prosper' },
      { zip: '75077', label: 'Little Elm' },
      { zip: '75068', label: 'Little Elm S' },
      { zip: '75056', label: 'The Colony' },
      { zip: '75065', label: 'Lake Dallas' },
      { zip: '76227', label: 'Aubrey' },
      { zip: '75009', label: 'Celina' },
      { zip: '75069', label: 'McKinney C' },
      { zip: '75025', label: 'Plano N' },
      { zip: '75023', label: 'Plano NW' },
      { zip: '75024', label: 'Plano NE' },
      { zip: '75094', label: 'Plano SE' },
      { zip: '75075', label: 'Plano C' },
      { zip: '75093', label: 'Plano W' },
    ],
  },
  {
    label: 'Central / Richardson',
    region: 'core_msa' as const,
    zips: [
      { zip: '75080', label: 'Richardson W' },
      { zip: '75081', label: 'Richardson E' },
      { zip: '75082', label: 'Richardson NE' },
      { zip: '75007', label: 'Carrollton N' },
      { zip: '75010', label: 'Carrollton E' },
      { zip: '75006', label: 'Carrollton W' },
      { zip: '75019', label: 'Coppell' },
      { zip: '75062', label: 'Irving' },
      { zip: '75038', label: 'Irving N' },
      { zip: '75063', label: 'Irving NW' },
      { zip: '75248', label: 'Addison' },
      { zip: '75252', label: 'Far N Dallas' },
      { zip: '75001', label: 'Addison N' },
      { zip: '75254', label: 'N Dallas' },
      { zip: '75287', label: 'N Dallas NW' },
    ],
  },
  {
    label: 'Irving / Las Colinas',
    region: 'core_msa' as const,
    zips: [
      { zip: '75039', label: 'Las Colinas' },
      { zip: '75060', label: 'Irving S' },
      { zip: '75061', label: 'Irving W' },
    ],
  },
  {
    label: 'Denton County',
    region: 'core_msa' as const,
    zips: [
      { zip: '76210', label: 'Denton S' },
      { zip: '76208', label: 'Denton' },
      { zip: '76209', label: 'Denton N' },
      { zip: '76201', label: 'Denton W' },
      { zip: '76203', label: 'Denton E' },
      { zip: '76205', label: 'Denton NE' },
      { zip: '76207', label: 'Denton SW' },
      { zip: '75028', label: 'Flower Mound' },
      { zip: '75022', label: 'Lewisville N' },
      { zip: '75057', label: 'Lewisville' },
      { zip: '75067', label: 'Lewisville S' },
      { zip: '76226', label: 'Argyle' },
      { zip: '76262', label: 'Trophy Club' },
      { zip: '76247', label: 'Justin' },
      { zip: '76249', label: 'Krum' },
      { zip: '76259', label: 'Ponder' },
      { zip: '76258', label: 'Pilot Point' },
      { zip: '76266', label: 'Sanger' },
    ],
  },
  {
    label: 'Tarrant / Mid-Cities',
    region: 'core_msa' as const,
    zips: [
      { zip: '76021', label: 'Bedford' },
      { zip: '76022', label: 'Bedford N' },
      { zip: '76034', label: 'Colleyville' },
      { zip: '76054', label: 'Hurst N' },
      { zip: '76006', label: 'Arlington NE' },
      { zip: '76005', label: 'Arlington NE' },
      { zip: '76010', label: 'Arlington E' },
      { zip: '76011', label: 'Arlington' },
      { zip: '76012', label: 'Arlington W' },
      { zip: '76013', label: 'Arlington C' },
      { zip: '76014', label: 'Arlington SE' },
      { zip: '76015', label: 'Arlington S' },
      { zip: '76016', label: 'Arlington SW' },
      { zip: '76017', label: 'Arlington S' },
      { zip: '76018', label: 'Arlington SE' },
      { zip: '76001', label: 'Arlington S' },
      { zip: '76063', label: 'Mansfield' },
      { zip: '76244', label: 'Keller' },
      { zip: '76248', label: 'Keller N' },
    ],
  },
  {
    label: 'Fort Worth Suburbs',
    region: 'core_msa' as const,
    zips: [
      { zip: '76104', label: 'Fort Worth SE' },
      { zip: '76108', label: 'Fort Worth W' },
      { zip: '76109', label: 'Fort Worth SW' },
      { zip: '76116', label: 'Fort Worth W' },
      { zip: '76118', label: 'Fort Worth E' },
      { zip: '76123', label: 'Fort Worth S' },
      { zip: '76131', label: 'Fort Worth NE' },
      { zip: '76133', label: 'Fort Worth S' },
      { zip: '76134', label: 'Fort Worth SW' },
      { zip: '76137', label: 'Fort Worth N' },
      { zip: '76179', label: 'Fort Worth NW' },
    ],
  },
  {
    label: 'Fort Worth City Core',
    region: 'core_msa' as const,
    zips: [
      { zip: '76102', label: 'Fort Worth' },
      { zip: '76103', label: 'Fort Worth E' },
      { zip: '76105', label: 'Fort Worth E' },
      { zip: '76106', label: 'Fort Worth N' },
      { zip: '76107', label: 'Fort Worth W' },
      { zip: '76110', label: 'Near Southside' },
      { zip: '76111', label: 'Fort Worth NE' },
      { zip: '76112', label: 'Fort Worth SE' },
      { zip: '76114', label: 'Westover Hills' },
      { zip: '76115', label: 'Fort Worth SW' },
      { zip: '76117', label: 'Haltom City' },
      { zip: '76119', label: 'Fort Worth SE' },
      { zip: '76120', label: 'Fort Worth E' },
      { zip: '76126', label: 'Benbrook' },
      { zip: '76129', label: 'Fort Worth' },
      { zip: '76132', label: 'Fort Worth S' },
      { zip: '76135', label: 'Lake Worth' },
      { zip: '76140', label: 'Everman' },
      { zip: '76148', label: 'Watauga' },
      { zip: '76155', label: 'Fort Worth NE' },
      { zip: '76164', label: 'Fort Worth N' },
      { zip: '76177', label: 'Fort Worth NW' },
      { zip: '76180', label: 'N Richland Hills' },
      { zip: '76182', label: 'N Richland Hills E' },
    ],
  },
  {
    label: 'Grand Prairie',
    region: 'core_msa' as const,
    zips: [
      { zip: '75050', label: 'Grand Prairie N' },
      { zip: '75051', label: 'Grand Prairie' },
      { zip: '75052', label: 'Grand Prairie S' },
      { zip: '75054', label: 'Grand Prairie SW' },
    ],
  },
  {
    label: 'Garland',
    region: 'core_msa' as const,
    zips: [
      { zip: '75041', label: 'Garland' },
      { zip: '75042', label: 'Garland NW' },
      { zip: '75044', label: 'Garland N' },
    ],
  },
  {
    label: 'Dallas City',
    region: 'core_msa' as const,
    zips: [
      { zip: '75206', label: 'Dallas NE' },
      { zip: '75214', label: 'Lakewood' },
      { zip: '75218', label: 'East Dallas' },
      { zip: '75216', label: 'Oak Cliff' },
      { zip: '75217', label: 'Dallas SE' },
      { zip: '75227', label: 'Dallas SE' },
      { zip: '75228', label: 'Dallas E' },
      { zip: '75238', label: 'Dallas NE' },
      { zip: '75246', label: 'Dallas' },
      { zip: '75270', label: 'Dallas C' },
    ],
  },
  {
    label: 'Dallas City Core',
    region: 'core_msa' as const,
    zips: [
      { zip: '75201', label: 'Downtown' },
      { zip: '75202', label: 'S Downtown' },
      { zip: '75203', label: 'S Dallas' },
      { zip: '75204', label: 'Uptown' },
      { zip: '75205', label: 'Highland Park' },
      { zip: '75207', label: 'Design District' },
      { zip: '75208', label: 'Kessler Park' },
      { zip: '75209', label: 'Bluffview' },
      { zip: '75210', label: 'S Dallas' },
      { zip: '75211', label: 'Oak Cliff W' },
      { zip: '75212', label: 'W Dallas' },
      { zip: '75215', label: 'S Dallas' },
      { zip: '75219', label: 'Oak Lawn' },
      { zip: '75220', label: 'Preston Hollow' },
      { zip: '75223', label: 'E Dallas' },
      { zip: '75224', label: 'N Oak Cliff' },
      { zip: '75225', label: 'Preston Hollow N' },
      { zip: '75226', label: 'Deep Ellum' },
      { zip: '75229', label: 'NW Dallas' },
      { zip: '75230', label: 'N Dallas' },
      { zip: '75231', label: 'NE Dallas' },
      { zip: '75232', label: 'Redbird' },
      { zip: '75233', label: 'SW Dallas' },
      { zip: '75234', label: 'Farmers Branch' },
      { zip: '75235', label: 'Medical District' },
      { zip: '75236', label: 'S Oak Cliff' },
      { zip: '75237', label: 'SW Dallas' },
      { zip: '75240', label: 'N Dallas' },
      { zip: '75241', label: 'S Dallas' },
      { zip: '75243', label: 'LB Freeway' },
      { zip: '75244', label: 'Addison S' },
      { zip: '75247', label: 'W Dallas' },
      { zip: '75249', label: 'SW Dallas' },
      { zip: '75251', label: 'Far S Dallas' },
      { zip: '75253', label: 'SE Dallas' },
    ],
  },
  {
    label: 'South Dallas Suburbs',
    region: 'core_msa' as const,
    zips: [
      { zip: '75104', label: 'Cedar Hill' },
      { zip: '75115', label: 'DeSoto' },
      { zip: '75116', label: 'Duncanville' },
      { zip: '75137', label: 'Duncanville S' },
      { zip: '75146', label: 'Lancaster' },
      { zip: '75134', label: 'Lancaster SE' },
      { zip: '75141', label: 'Hutchins' },
      { zip: '75172', label: 'Wilmer' },
      { zip: '75165', label: 'Waxahachie' },
      { zip: '75167', label: 'Waxahachie W' },
      { zip: '75154', label: 'Red Oak' },
      { zip: '75125', label: 'Ferris' },
      { zip: '75152', label: 'Palmer' },
    ],
  },
  {
    label: 'Ellis County',
    region: 'core_msa' as const,
    zips: [
      { zip: '76065', label: 'Midlothian' },
      { zip: '75119', label: 'Ennis' },
      { zip: '76084', label: 'Venus' },
      { zip: '76064', label: 'Maypearl' },
      { zip: '75101', label: 'Bardwell' },
      { zip: '76623', label: 'Avalon' },
      { zip: '76670', label: 'Milford' },
      { zip: '76651', label: 'Italy' },
      { zip: '76041', label: 'Forreston' },
    ],
  },
  {
    label: 'Johnson County',
    region: 'core_msa' as const,
    zips: [
      { zip: '76028', label: 'Burleson' },
      { zip: '76036', label: 'Crowley' },
      { zip: '76009', label: 'Alvarado' },
      { zip: '76058', label: 'Joshua' },
      { zip: '76059', label: 'Keene' },
      { zip: '76050', label: 'Grandview' },
      { zip: '76031', label: 'Cleburne' },
      { zip: '76033', label: 'Cleburne S' },
      { zip: '76044', label: 'Godley' },
      { zip: '76061', label: 'Lillian' },
      { zip: '76093', label: 'Rio Vista' },
    ],
  },
  {
    label: 'Parker County',
    region: 'core_msa' as const,
    zips: [
      { zip: '76008', label: 'Aledo' },
      { zip: '76020', label: 'Azle' },
      { zip: '76023', label: 'Boyd' },
      { zip: '76035', label: 'Cresson' },
      { zip: '76066', label: 'Millsap' },
      { zip: '76073', label: 'Paradise' },
      { zip: '76078', label: 'Rhome' },
      { zip: '76082', label: 'Springtown' },
      { zip: '76085', label: 'Weatherford' },
      { zip: '76086', label: 'Weatherford' },
      { zip: '76087', label: 'Weatherford W' },
      { zip: '76088', label: 'Weatherford N' },
      { zip: '76462', label: 'Lipan' },
      { zip: '76476', label: 'Tolar' },
      { zip: '76486', label: 'Perrin' },
      { zip: '76487', label: 'Poolville' },
      { zip: '76490', label: 'Whitt' },
    ],
  },
  {
    label: 'Wise County',
    region: 'core_msa' as const,
    zips: [
      { zip: '76052', label: 'Haslet' },
      { zip: '76071', label: 'Newark' },
      { zip: '76225', label: 'Alvord' },
      { zip: '76234', label: 'Decatur' },
      { zip: '76267', label: 'Slidell' },
      { zip: '76270', label: 'Sunset' },
      { zip: '76426', label: 'Bridgeport' },
      { zip: '76431', label: 'Chico' },
    ],
  },
  {
    label: 'Hood County',
    region: 'extended' as const,
    zips: [
      { zip: '76048', label: 'Granbury' },
      { zip: '76049', label: 'Granbury E' },
      { zip: '76043', label: 'Glen Rose' },
      { zip: '76077', label: 'Rainbow' },
      { zip: '76070', label: 'Nemo' },
      { zip: '76652', label: 'Kopperl' },
    ],
  },
  {
    label: 'Cooke / Montague County',
    region: 'extended' as const,
    zips: [
      { zip: '76238', label: 'Era' },
      { zip: '76240', label: 'Gainesville' },
      { zip: '76241', label: 'Gainesville N' },
      { zip: '76250', label: 'Lindsay' },
      { zip: '76252', label: 'Muenster' },
      { zip: '76253', label: 'Myra' },
      { zip: '76272', label: 'Valley View' },
      { zip: '76239', label: 'Forestburg' },
    ],
  },
  {
    label: 'Collin County North',
    region: 'core_msa' as const,
    zips: [
      { zip: '75407', label: 'Princeton' },
      { zip: '75454', label: 'Melissa' },
      { zip: '75409', label: 'Anna' },
      { zip: '75442', label: 'Farmersville' },
      { zip: '75424', label: 'Blue Ridge' },
      { zip: '75164', label: 'Josephine' },
      { zip: '75423', label: 'Celeste' },
    ],
  },
  {
    label: 'Grayson County',
    region: 'extended' as const,
    zips: [
      { zip: '75020', label: 'Denison' },
      { zip: '75021', label: 'Denison E' },
      { zip: '75058', label: 'Gunter' },
      { zip: '75076', label: 'Pottsboro' },
      { zip: '75090', label: 'Sherman' },
      { zip: '75092', label: 'Sherman N' },
      { zip: '75413', label: 'Bailey' },
      { zip: '75414', label: 'Bells' },
      { zip: '75439', label: 'Ector' },
      { zip: '75459', label: 'Howe' },
      { zip: '75475', label: 'Randolph' },
      { zip: '75476', label: 'Ravenna' },
      { zip: '75479', label: 'Savoy' },
      { zip: '75489', label: 'Tom Bean' },
      { zip: '75491', label: 'Whitewright' },
      { zip: '75492', label: 'Windom' },
      { zip: '75495', label: 'Van Alstyne' },
      { zip: '76233', label: 'Collinsville' },
      { zip: '76245', label: 'Gordonville' },
      { zip: '76264', label: 'Sadler' },
      { zip: '76268', label: 'Southmayd' },
      { zip: '76271', label: 'Tioga' },
      { zip: '76273', label: 'Whitesboro' },
    ],
  },
  {
    label: 'Fanin County',
    region: 'extended' as const,
    zips: [
      { zip: '75418', label: 'Bonham' },
      { zip: '75438', label: 'Dodd City' },
      { zip: '75448', label: 'Klondike' },
      { zip: '75449', label: 'Ladonia' },
      { zip: '75452', label: 'Leonard' },
      { zip: '75469', label: 'Pecan Gap' },
      { zip: '75490', label: 'Trenton' },
    ],
  },
  {
    label: 'Hunt County',
    region: 'core_msa' as const,
    zips: [
      { zip: '75401', label: 'Greenville' },
      { zip: '75402', label: 'Greenville S' },
      { zip: '75422', label: 'Campbell' },
      { zip: '75428', label: 'Commerce' },
      { zip: '75429', label: 'Commerce E' },
      { zip: '75433', label: 'Cumby' },
      { zip: '75453', label: 'Lone Oak' },
      { zip: '75474', label: 'Quinlan' },
      { zip: '75496', label: 'Wolfe City' },
    ],
  },
  {
    label: 'Kaufman County',
    region: 'core_msa' as const,
    zips: [
      { zip: '75142', label: 'Kaufman' },
      { zip: '75143', label: 'Kemp' },
      { zip: '75157', label: 'Rosser' },
      { zip: '75158', label: 'Scurry' },
    ],
  },
  {
    label: 'Van Zandt / Rains County',
    region: 'extended' as const,
    zips: [
      { zip: '75103', label: 'Canton' },
      { zip: '75117', label: 'Edgewood' },
      { zip: '75124', label: 'Eustace' },
      { zip: '75127', label: 'Fruitvale' },
      { zip: '75140', label: 'Grand Saline' },
      { zip: '75147', label: 'Mabank' },
      { zip: '75169', label: 'Wills Point' },
      { zip: '75472', label: 'Point' },
      { zip: '75497', label: 'Yantis' },
      { zip: '75754', label: 'Ben Wheeler' },
      { zip: '75778', label: 'Murchison' },
      { zip: '75790', label: 'Van' },
    ],
  },
  {
    label: 'Henderson County',
    region: 'extended' as const,
    zips: [
      { zip: '75148', label: 'Malakoff' },
      { zip: '75156', label: 'Mabank' },
      { zip: '75163', label: 'Trinidad' },
      { zip: '75752', label: 'Athens' },
      { zip: '75751', label: 'Athens S' },
    ],
  },
  {
    label: 'Navarro County',
    region: 'extended' as const,
    zips: [
      { zip: '75102', label: 'Barry' },
      { zip: '75105', label: 'Chatfield' },
      { zip: '75109', label: 'Corsicana' },
      { zip: '75110', label: 'Corsicana N' },
      { zip: '75153', label: 'Powell' },
      { zip: '75155', label: 'Rice' },
      { zip: '75859', label: 'Streetman' },
      { zip: '75848', label: 'Kirvin' },
      { zip: '76626', label: 'Blooming Grove' },
      { zip: '76628', label: 'Brandon' },
      { zip: '76631', label: 'Bynum' },
      { zip: '76636', label: 'Covington' },
      { zip: '76639', label: 'Dawson' },
      { zip: '76641', label: 'Frost' },
      { zip: '76650', label: 'Irene' },
      { zip: '76676', label: 'Penelope' },
      { zip: '76679', label: 'Purdon' },
      { zip: '76693', label: 'Wortham' },
    ],
  },
  {
    label: 'Hill County',
    region: 'extended' as const,
    zips: [
      { zip: '76055', label: 'Itasca' },
      { zip: '76621', label: 'Abbott' },
      { zip: '76622', label: 'Aquilla' },
      { zip: '76627', label: 'Blum' },
      { zip: '76645', label: 'Hillsboro' },
      { zip: '76648', label: 'Hubbard' },
      { zip: '76654', label: 'Leroy' },
      { zip: '76660', label: 'Malone' },
      { zip: '76666', label: 'Mertens' },
      { zip: '76671', label: 'Morgan' },
      { zip: '76673', label: 'Mount Calm' },
      { zip: '76686', label: 'Tehuacana' },
      { zip: '76691', label: 'West' },
      { zip: '76692', label: 'Whitney' },
    ],
  },
  {
    label: 'Hopkins / Wood County',
    region: 'extended' as const,
    zips: [
      { zip: '75410', label: 'Alba' },
      { zip: '75420', label: 'Brashear' },
      { zip: '75440', label: 'Emory' },
      { zip: '75482', label: 'Sulphur Springs' },
    ],
  },
  {
    label: 'Suburban Fill',
    region: 'core_msa' as const,
    zips: [
      { zip: '76002', label: 'Arlington SW' },
      { zip: '76039', label: 'Euless' },
      { zip: '76040', label: 'Euless S' },
      { zip: '76051', label: 'Grapevine' },
      { zip: '76053', label: 'Hurst' },
      { zip: '76060', label: 'Kennedale' },
      { zip: '76092', label: 'Southlake' },
      { zip: '75166', label: 'Lavon' },
      { zip: '75173', label: 'Nevada' },
    ],
  },
]

export const DFW_ZIPS = ZIP_GROUPS.flatMap(g => g.zips.map(z => ({ ...z, region: g.region })))
export type ZipEntry = (typeof DFW_ZIPS)[number]

export const CORE_MSA_ZIPS = DFW_ZIPS.filter(z => z.region === 'core_msa')
export const CORE_MSA_ZIP_SET = new Set(CORE_MSA_ZIPS.map(z => z.zip))

// ZIPs where the ZCTA boundary changed between the 2020 Census and 2023 ACS.
// Growth comparisons for these ZIPs are invalid (boundary artifact, not real decline).
// Confirmed splits: 75070 (McKinney W → 75071/75072), 75034 (Frisco W → 75033/75036)
// Needs verification vs. Census ZCTA relationship file: 75132, 76061, 76623, 76490, 75157
export const BOUNDARY_CHANGED = new Set([
  '75070', '75034',
  '75132', '76061', '76623', '76490', '75157',
])

// Lakepointe campus presence — keyed by ZIP
export const CAMPUS_ZIPS: Record<string, 'existing' | 'soon'> = {
  '75087': 'existing', // Rockwall
  '75150': 'existing', // Mesquite
  '75044': 'existing', // Firewheel
  '75126': 'existing', // Forney
  '75251': 'existing', // North Dallas
  '75218': 'existing', // East Dallas
  '75182': 'existing', // Sunnyvale
  '75189': 'existing', // Royse City
  '75002': 'soon',     // Lucas / Allen
  '75401': 'soon',     // Greenville
}
